export const TOGGLE_SIDEBAR_STATUS = 'TOGGLE_SIDEBAR_STATUS'
export const SET_CATEGORIES = 'SET_CATEGORIES'
export const SET_QUESTIONS_TYPES = 'SET_QUESTIONS_TYPES'
export const ADD_QUIZ = 'ADD_QUIZ'
